# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='110030', max_length=50),
        ),
    ]
