# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-07 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
